# Generated by Django 5.2.5 on 2025-08-25 13:19

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blood_Type',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('modified_at', models.DateTimeField(auto_now=True, db_column='modified_at')),
                ('active', models.BooleanField(db_column='active', default=True)),
                ('name', models.CharField(choices=[('A+', 'A+'), ('AB+', 'AB+'), ('A-', 'A-'), ('O-', 'O-'), ('AB-', 'AB-'), ('O+', 'O+'), ('B-', 'B-'), ('B+', 'B+')], db_column='tx_name', default='O+', max_length=255)),
            ],
            options={
                'verbose_name': 'Blood Type',
                'verbose_name_plural': 'Blood Types',
                'db_table': 'blood_type',
            },
        ),
        migrations.CreateModel(
            name='HealthInsurance',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('modified_at', models.DateTimeField(auto_now=True, db_column='modified_at')),
                ('active', models.BooleanField(db_column='active', default=True)),
                ('name', models.CharField(db_column='tx_name', max_length=120)),
            ],
            options={
                'verbose_name': 'Health Insurance',
                'verbose_name_plural': 'Health Insurances',
                'db_table': 'health_insurance',
            },
        ),
        migrations.CreateModel(
            name='Medic',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('modified_at', models.DateTimeField(auto_now=True, db_column='modified_at')),
                ('active', models.BooleanField(db_column='active', default=True)),
                ('crm', models.CharField(db_column='tx_crm', max_length=120, unique=True)),
            ],
            options={
                'verbose_name': 'Medic',
                'verbose_name_plural': 'Medics',
                'db_table': 'medic',
            },
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('modified_at', models.DateTimeField(auto_now=True, db_column='modified_at')),
                ('active', models.BooleanField(db_column='active', default=True)),
                ('name', models.CharField(db_column='tx_name', max_length=255)),
                ('type_application', models.CharField(choices=[('2-', 'injectable'), ('1-', 'oral')], db_column='type_application', max_length=40)),
                ('type_dosage', models.CharField(choices=[('1-', '1ml'), ('2-', '2mg')], db_column='type_dosage', max_length=40)),
            ],
            options={
                'verbose_name': 'Medication',
                'verbose_name_plural': 'Medications',
                'db_table': 'medication',
            },
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('modified_at', models.DateTimeField(auto_now=True, db_column='modified_at')),
                ('active', models.BooleanField(db_column='active', default=True)),
                ('name', models.CharField(db_column='tx_name', max_length=210)),
            ],
            options={
                'verbose_name': 'Specialization',
                'verbose_name_plural': 'Specializations',
                'db_table': 'specialization',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='tx_name', max_length=255)),
                ('date_birth', models.DateField(db_column='dt_date_birth')),
                ('email', models.EmailField(db_column='tx_email', max_length=254, unique=True)),
                ('sex', models.CharField(choices=[('male', 'male'), ('female', 'female')], db_column='tx_sex', max_length=10)),
                ('cpf', models.CharField(db_column='tx_cpf', max_length=11, unique=True)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('modified_at', models.DateTimeField(auto_now=True, db_column='modified_at')),
                ('active', models.BooleanField(db_column='active', default=True)),
                ('time_consultation', models.DateTimeField(db_column='datetime')),
                ('diagnosis', models.TextField(db_column='tx_diagnosis', max_length=255)),
                ('medic_attended', models.BooleanField(db_column='cs_medic_attended')),
                ('patient_attended', models.BooleanField(db_column='cs_patient_attended')),
                ('medic', models.ForeignKey(db_column='id_medic', on_delete=django.db.models.deletion.PROTECT, to='core.medic')),
            ],
            options={
                'verbose_name': 'Consultation',
                'verbose_name_plural': 'Consultations',
                'db_table': 'consultation',
            },
        ),
        migrations.CreateModel(
            name='MedicationConsultation',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('modified_at', models.DateTimeField(auto_now=True, db_column='modified_at')),
                ('active', models.BooleanField(db_column='active', default=True)),
                ('dosage', models.IntegerField(db_column='dosage')),
                ('consultation', models.ForeignKey(db_column='id_consultation', on_delete=django.db.models.deletion.CASCADE, to='core.consultation')),
                ('medication', models.ForeignKey(db_column='id_medication', on_delete=django.db.models.deletion.PROTECT, to='core.medication')),
            ],
            options={
                'verbose_name': 'Medication Consultation',
                'verbose_name_plural': 'Medication Consultations',
                'db_table': 'medication_consultation',
            },
        ),
        migrations.AddField(
            model_name='consultation',
            name='medication',
            field=models.ManyToManyField(through='core.MedicationConsultation', to='core.medication'),
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('modified_at', models.DateTimeField(auto_now=True, db_column='modified_at')),
                ('active', models.BooleanField(db_column='active', default=True)),
                ('weight', models.DecimalField(db_column='nb_weight', decimal_places=2, max_digits=5)),
                ('height', models.IntegerField(db_column='nb_height', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(300)])),
                ('blood_type', models.ForeignKey(db_column='id_blood_type', on_delete=django.db.models.deletion.PROTECT, to='core.blood_type')),
                ('user', models.ForeignKey(db_column='id_user', on_delete=django.db.models.deletion.CASCADE, to='core.user')),
            ],
            options={
                'verbose_name': 'Patient',
                'verbose_name_plural': 'Patients',
                'db_table': 'patient',
            },
        ),
        migrations.AddField(
            model_name='consultation',
            name='patient',
            field=models.ForeignKey(db_column='id_patient', on_delete=django.db.models.deletion.PROTECT, to='core.patient'),
        ),
        migrations.CreateModel(
            name='PatientHealthInsurance',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('modified_at', models.DateTimeField(auto_now=True, db_column='modified_at')),
                ('active', models.BooleanField(db_column='active', default=True)),
                ('insurance_number', models.CharField(db_column='insurance_number', max_length=120)),
                ('type', models.CharField(choices=[('nursery', 'nursery'), ('apartment', 'apartment')], db_column='type', max_length=255)),
                ('waiting_period', models.DateField(db_column='dt_waiting_period')),
                ('health_insurance', models.ForeignKey(db_column='id_health_insurance', on_delete=django.db.models.deletion.PROTECT, to='core.healthinsurance')),
                ('patient', models.ForeignKey(db_column='id_patient', on_delete=django.db.models.deletion.CASCADE, to='core.patient')),
            ],
            options={
                'verbose_name': 'Patient Health Insurance',
                'verbose_name_plural': 'Patients Health Insurances',
                'db_table': 'patient_health_insurance',
            },
        ),
        migrations.AddField(
            model_name='medic',
            name='specialization',
            field=models.ManyToManyField(db_table='specialization_medic', to='core.specialization'),
        ),
        migrations.CreateModel(
            name='Telephone',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('modified_at', models.DateTimeField(auto_now=True, db_column='modified_at')),
                ('active', models.BooleanField(db_column='active', default=True)),
                ('number', models.CharField(db_column='tx_number', max_length=11, unique=True)),
                ('user', models.ForeignKey(db_column='id_user', on_delete=django.db.models.deletion.CASCADE, to='core.user')),
            ],
            options={
                'verbose_name': 'Telephone',
                'verbose_name_plural': 'Telephones',
                'db_table': 'telephone',
            },
        ),
        migrations.AddField(
            model_name='medic',
            name='user',
            field=models.ForeignKey(db_column='id_user', on_delete=django.db.models.deletion.CASCADE, to='core.user'),
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('modified_at', models.DateTimeField(auto_now=True, db_column='modified_at')),
                ('active', models.BooleanField(db_column='active', default=True)),
                ('postal_code', models.CharField(db_column='tx_postal_code', max_length=8)),
                ('number_house', models.CharField(db_column='tx_number_house', max_length=10)),
                ('user', models.ForeignKey(db_column='id_user', on_delete=django.db.models.deletion.CASCADE, to='core.user')),
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': 'Addresses',
                'db_table': 'address',
            },
        ),
    ]
